on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ppc64le
          distro: ubuntu18.04

      # Set an output parameter `uname` for use in subsequent steps
      - name: ARCH  
        run: |
          uname -a
          echo $(uname -a)
